# Generated by Django 6.0.2 on 2026-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('upi', 'UPI Payment'), ('wallet', 'Digital Wallet')], default='cod', max_length=20),
        ),
    ]
